# Generated by Django 3.2 on 2021-05-03 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_patient_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.client'),
        ),
    ]
