# Generated by Django 3.2 on 2021-05-03 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_patient_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active_substance', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('dose', models.FloatField()),
                ('times_a_day', models.IntegerField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.patient')),
            ],
        ),
    ]
