# Generated by Django 3.2 on 2021-06-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_patient_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='database.patient'),
        ),
    ]
